on: 
  workflow_dispatch:
    inputs:
        message:
name: Bot
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - uses: Ilshidur/action-discord@master
          with:
           args: "${{ github.event.inputs.message }}"
          env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
